version: '3.8'

services:
  etl-loaddata:
    image: ubuntu-pi-03.local:5000/cryptoloader:latest
    hostname: etl-firstattempt
    container_name: etl-firstattempt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.workerid != 3
      restart_policy:
        condition: on-failure
    volumes:
      - etl_data:/glustervol1
      - /home/ubuntu/.ssh:/home/appuser/.ssh:ro
    networks:
      - springboot-crypto_crypto-network
      - spark-hadoop_cluster-network
      - rabbitmq_queue-net
  spark-job:
    image: ubuntu-pi-03.local:5000/cryptoloader:latest
    hostname: spark-firstattempt
    container_name: spark-firstattempt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.workerid != 3
      restart_policy:
        condition: on-failure
    volumes:
      - etl_data:/glustervol1
    environment:
      - HADOOP_CONF_DIR=/opt/spark/conf
      - YARN_CONF_DIR=/opt/spark/conf
    networks:
      - spark-hadoop_cluster-network
      - rabbitmq_queue-net

volumes:
  etl_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/glusterfs

networks:
  springboot-crypto_crypto-network:
    external: true
  spark-hadoop_cluster-network:
    external: true
  rabbitmq_queue-net:
    external: true
